export const CREATE_FILE = 'CREATE_FILE';
export const UPDATE_FILE = 'UPDATE_FILE';
export const DELETE_FILE = 'DELETE_FILE';
export const UPLOAD_FILE = 'UPLOAD_FILE';

export const CREATE_RESPONSE = 'CREATE_RESPONSE';
export const UPDATE_RESPONSE = 'UPDATE_RESPONSE';
export const RECORD_RESPONSE = 'RECORD_RESPONSE';
export const SUBMIT_RESPONSE = 'SUBMIT_RESPONSE';
export const RESPONSE_SUBMITTED = 'RESPONSE_SUBMITTED';
export const FAILED_SUBMISSION = 'FAILED_SUBMISSION';
export const DELETE_RESPONSE = 'DELETE_RESPONSE';
